// angular-todo-framework/src/app/list-item/list-item.component.ts
import { Component, Input } from '@angular/core';

@Component({
    selector: 'list-item',
    templateUrl: './list-item.component.html',
    styleUrls: ['./list-item.component.css']
})
export class ListItemComponent {
    private _content = '';

    @Input()
    set content(content: string) {
        this._content = content;
    }

    get content(): string { return this._content; }

    isDone = 'logo';
    id = 'logo';

    share() {
        window.alert('The product has been shared!');
    }
}
<li class="c-list-item">
    <div class="o-grid">
        <div>
            <label for="inputId" class="is-visually-hidden">Mark Item {{id}} as done</label>
            <input type="checkbox" class="c-checkbox" name="items" id="inputId" checked>
        </div>
        <div class="o-grid__full">{{content}}</div>
        <div>
            <button type="button" class="c-button">
                <icon icon="remove"></icon>
            </button>
        </div>
    </div>
</li>

// react-todo-framework/src/components/listitem/listitem.js
import React from 'react';
import Icon from '../icon/icon';

class ListItem extends React.Component {
    render() {
        const data = this.props.data;
        const isDone = data.isDone ? '--done' : '';
        return (
            <li className={"c-list-item " + isDone}>
                <div className="o-grid">
                    <div>
                        <label htmlFor={"item" + data.id} className="is-visually-hidden">Mark Item as done</label>
                        <input
                            type="checkbox"
                            className="c-checkbox"
                            id={"item" + data.id}
                            name="items"
                            onClick={() => {}}
                            defaultChecked={data.isDone}
                        />
                    </div>
                    <div className="o-grid__full">{data.content}</div>
                    <div>
                        <button type="button" className="c-button">
                            <Icon icon="remove" />
                        </button>
                    </div>
                </div>
            </li>
        )
    }
}

export default ListItem;
